#server:
#  port: 9091
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://35.225.77.4:5432/UserDB
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update

 ## bu bilgiler art覺k config server 覺n icindeki config-repo kisminda
 ## bu bilgileri kullanmak istiyorsan config-server 覺 iptal etmen la覺zm

# config server ile ayaga kalkma :
spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: user-micro-service
