#server:
#  port: 9090
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://35.225.77.4:5432/AuthDB
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#
  ## bu bilgiler artık config server ın icindeki config-repo kisminda
  # configden cagirma islemi burada

spring:
  zipkin:
    enabled: true
    base-url: hhtp://localhost:9411
    service:
      name: auth-micro-server
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: auth-micro-service
